---
abstract: 'Object-oriented access to hash with implicitly typed fields'
author:
  - 'Nat Goodman <natg@shore.net>'
build_requires:
  Exporter: 5.58
  Test::Deep: 0.098
  Test::More: 0.88
  perl: v5.17.6
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-AutoHash-Record
provides:
  Hash::AutoHash::Record:
    file: lib/Hash/AutoHash/Record.pm
    version: 1.16_01
  Hash::AutoHash::Record::helper:
    file: lib/Hash/AutoHash/Record.pm
    version: 0
  Hash::AutoHash::Record::tie:
    file: lib/Hash/AutoHash/Record.pm
    version: 0
requires:
  Carp: 0
  Hash::AutoHash: 1.15
  Hash::AutoHash::AVPairsMulti: 1.14
  Hash::AutoHash::AVPairsSingle: 1.14
  List::MoreUtils: 0.09
  Scalar::Util: 1.01
  Storable: 2.16
  Tie::Hash: 1
resources:
  license: http://dev.perl.org/licenses/
version: 1.16_01
